name: CI

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          git clone https://gitlab.com/tearch-linux/applications-and-tools/teaiso
          cd teaiso
          sudo apt install xorriso grub-pc-bin grub-efi mtools make python3 \
              dosfstools e2fsprogs squashfs-tools python3-yaml \
              gcc wget curl unzip xz-utils zstd debootstrap -y
          sudo make
          sudo ln -s sid /usr/share/debootstrap/scripts/yirmibir
          sudo ./mkteaiso --profile=../pardus --output=/output/ --debug 2>&1


      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Auto build"
          files: |
            /output/*




